-- Hackathons: MLH 2027-season events in the NJ/NYC area plus major national hackathons.
-- Event dates come from the MLH 2027 season schedule (https://www.mlh.com/seasons/2027/events),
-- checked 2026-09-02. Application windows were verified per-event where a date is given.
-- Idempotent: safe to run more than once (matches on title).

insert into public.programs (
  title, description, tag, eligibility, image, link,
  timeline_status, timeline, previous_timeline,
  opens_on, closes_on, sort_order, deadline, source_checked_on
)
select
  v.title, v.description, v.tag, v.eligibility, v.image, v.link,
  v.timeline_status, v.timeline, v.previous_timeline,
  v.opens_on, v.closes_on, v.sort_order, v.timeline, date '2026-09-02'
from (
  values
    (
      'GirlHacks',
      '24-hour hackathon run by NJIT’s Women in Computing Society, built around women and non-binary hackers. Beginner friendly, and all genders may attend.',
      'Hackathon',
      'College Students / All Skill Levels',
      '/resources/hackathons/girlhacks.png',
      'https://www.njitgirlhacks.com/',
      'Open now',
      'Registration closes Sep 9, 2026; event runs Oct 3-4',
      'Deadline confirmed on the GirlHacks site. Held annually at NJIT each fall.',
      null::date,
      date '2026-09-09',
      20
    ),
    (
      'Cal Hacks 13.0',
      'Berkeley’s flagship 36-hour hackathon, one of the largest collegiate hackathons in the world, held at the Palace of Fine Arts in San Francisco.',
      'Hackathon',
      'Undergrad, Grad & New Grads (<1 Year)',
      '/resources/hackathons/cal-hacks-13.png',
      'https://www.calhacks.io/',
      'Open now',
      'Priority deadline Sep 13; regular deadline Sep 20, 2026',
      'Priority decisions Sep 17, regular decisions Sep 25. Students who graduated before Fall 2025 do not qualify.',
      null::date,
      date '2026-09-20',
      21
    ),
    (
      'DivHacks',
      'Columbia’s 32-hour diversity hackathon. The 2026 theme, "Concrete Jungle," focuses on food, housing, and transportation in the communities we live in.',
      'Hackathon',
      'Any College Student, 18+',
      '/resources/hackathons/divhacks.png',
      'https://www.columbiadivhacks.org/',
      'Open now',
      'Applications open now; event runs Sep 26-27, 2026',
      'No published cutoff date — DivHacks accepts applications until it fills. No coding experience or CS major required.',
      null::date,
      null::date,
      22
    ),
    (
      'HackHarvard',
      'A 36-hour undergraduate hackathon drawing 500+ students worldwide to Harvard’s campus, with tracks spanning health, climate, and civic tech.',
      'Hackathon',
      'Undergraduate Students',
      '/resources/hackathons/hackharvard.png',
      'https://www.hhuh.io/',
      'Open now',
      'Applications open now; event runs Oct 16-18, 2026',
      'Harvard is not providing overnight housing this year; plan lodging yourself. Financial aid details are shared with accepted hackers.',
      null::date,
      null::date,
      23
    ),
    (
      'Hack Knight',
      'CUNY Queens College’s student-run diversity hackathon, one of the most accessible entry points into hackathons for NYC commuter students.',
      'Hackathon',
      'College Students / All Skill Levels',
      '/resources/hackathons/hack-knight.png',
      'https://hack-knight.devpost.com/',
      'Opens soon',
      'Event runs Oct 9-11, 2026; application date not published',
      'The Fall 2025 edition ran Oct 17-19 at Queens College.',
      null::date,
      null::date,
      24
    ),
    (
      'SBUHacks',
      'Stony Brook’s largest annual hackathon, where student teams build themed projects from scratch over a weekend on Long Island.',
      'Hackathon',
      'College Students / All Skill Levels',
      '/resources/hackathons/sbuhacks.png',
      'https://hack.sbcs.io/',
      'Open now',
      'Applications open now; event runs Oct 23-25, 2026',
      'This is Stony Brook’s 6th student-run hackathon. No cutoff date published.',
      null::date,
      null::date,
      25
    ),
    (
      'MakeCU',
      'Columbia Robotics Club’s 24-hour hardware hackathon — a rare build-with-your-hands event in NYC, with parts, workshops, and mentors provided.',
      'Hardware',
      'Undergraduate through PhD',
      '/resources/hackathons/makecu.png',
      'https://www.makecu.dev/',
      'Opens soon',
      'Event runs Nov 7-8, 2026; application date not published',
      'Beginners are explicitly welcome — workshops and mentors help you learn hardware during the event.',
      null::date,
      null::date,
      26
    ),
    (
      'BigRed//Hacks',
      'Cornell’s flagship student-run hackathon, a weekend-long build in Ithaca that draws teams from across the Northeast.',
      'Hackathon',
      'College Students / All Skill Levels',
      '/resources/hackathons/bigred-hacks.png',
      'https://www.bigredhacks.com/',
      'Open now',
      'Event runs Oct 2-4, 2026; apply on the event site',
      'Listed on the MLH 2027 season schedule. No public application cutoff date.',
      null::date,
      null::date,
      27
    ),
    (
      'HackRPI 2026',
      'RPI’s 13th annual intercollegiate hackathon, themed "In the Clouds." Free to attend with food, swag, and prizes, open to any school or major.',
      'Hackathon',
      'All Students / Any Major',
      '/resources/hackathons/hackrpi.png',
      'https://www.hackrpi.com/',
      'Opens soon',
      'Event runs Nov 7-8, 2026; register through MLH',
      'Free to attend and open to students from all schools regardless of major or experience level.',
      null::date,
      null::date,
      28
    ),
    (
      'HackHERS',
      'Rutgers’ diversity-focused hackathon centering women and non-binary students, and the main spring hackathon in central New Jersey.',
      'Hackathon',
      'College Students / All Skill Levels',
      '/resources/hackathons/hackhers.png',
      'https://www.mlh.com/seasons/2027/events',
      'Expected',
      'Event set for Feb 27-28, 2027; applications expected Jan 2027',
      'Confirmed on the MLH 2027 season schedule. Spring hackathons typically open applications 4-6 weeks ahead.',
      null::date,
      null::date,
      29
    ),
    (
      'WiCHacks',
      'RIT’s all-women and non-binary hackathon, one of the longest-running diversity hackathons in New York State.',
      'Hackathon',
      'College Students / All Skill Levels',
      '/resources/hackathons/wichacks.png',
      'https://www.mlh.com/seasons/2027/events',
      'Expected',
      'Event set for Feb 27-28, 2027; applications expected Jan 2027',
      'Confirmed on the MLH 2027 season schedule.',
      null::date,
      null::date,
      30
    ),
    (
      'ShellHacks',
      'Florida’s largest hackathon, hosted by INIT at FIU, drawing well over a thousand students to Miami each fall.',
      'Hackathon',
      'College Students / All Skill Levels',
      '/resources/hackathons/shellhacks.png',
      'https://shellhacks.net/',
      'Open now',
      'Event runs Sep 25-27, 2026; register at shellhacks.net',
      'Confirmed on the MLH 2027 season schedule. No public application cutoff date.',
      null::date,
      null::date,
      31
    ),
    (
      'Knight Hacks IX',
      'UCF’s 36-hour flagship hackathon built around curiosity, creativity, and community, and one of the biggest in the Southeast.',
      'Hackathon',
      'College Students / All Skill Levels',
      '/resources/hackathons/knight-hacks.png',
      'https://2026.knighthacks.org/',
      'Open now',
      'Event runs Oct 9-11, 2026; apply at 2026.knighthacks.org',
      'Confirmed on the MLH 2027 season schedule. No public application cutoff date.',
      null::date,
      null::date,
      32
    ),
    (
      'SwampHacks XII',
      'UF’s long-running hackathon, now in its twelfth year, bringing student teams to Gainesville for a weekend build.',
      'Hackathon',
      'College Students / All Skill Levels',
      '/resources/hackathons/swamphacks.png',
      'https://swamphacks.com/',
      'Open now',
      'Event runs Oct 16-18, 2026; hacker applications open in July',
      'Confirmed on the MLH 2027 season schedule. SwampHacks historically opens hacker applications in July.',
      null::date,
      null::date,
      33
    ),
    (
      'Gator Quant Hacks',
      'A quantitative-finance hackathon at UF for students targeting trading, quant research, and financial engineering roles.',
      'Quant',
      'College Students / Quant Interest',
      '/resources/hackathons/gator-quant-hacks.png',
      'https://www.mlh.com/seasons/2027/events',
      'Open now',
      'Event runs Oct 2-4, 2026; apply through the event site',
      'Listed as a diversity event on the MLH 2027 season schedule.',
      null::date,
      null::date,
      34
    ),
    (
      'LA Hacks AI Hackathon',
      'The fall AI-focused edition run by the LA Hacks team, a shorter companion event to their spring flagship at UCLA.',
      'Hackathon',
      'College Students / All Skill Levels',
      '/resources/hackathons/la-hacks-ai.png',
      'https://www.lahacks.com/',
      'Open now',
      'Event runs Oct 17-18, 2026; apply at lahacks.com',
      'Confirmed on the MLH 2027 season schedule.',
      null::date,
      null::date,
      35
    ),
    (
      'TreeHacks',
      'Stanford’s flagship hackathon and one of the most selective in the world, covering meals, travel, and lodging for accepted hackers.',
      'Hackathon',
      'College Students / Highly Selective',
      '/resources/hackathons/treehacks.png',
      'https://www.treehacks.com/',
      'Expected',
      'Applications expected Nov 2026 for a Feb 2027 event',
      'TreeHacks 2026 ran Feb 13-15, 2026 and drew builders from ~30 universities across 12 countries. 2027 dates are not confirmed on the official site.',
      null::date,
      null::date,
      36
    ),
    (
      'SF Hacks',
      'San Francisco State’s student-run hackathon, an accessible Bay Area option that draws heavily from local startups for mentorship.',
      'Hackathon',
      'College Students / All Skill Levels',
      '/resources/hackathons/sf-hacks.png',
      'https://www.mlh.com/seasons/2027/events',
      'Expected',
      'Event set for Feb 19-21, 2027; applications expected Jan 2027',
      'Confirmed on the MLH 2027 season schedule.',
      null::date,
      null::date,
      37
    ),
    (
      'Diamondhacks',
      'UC San Diego’s spring hackathon in La Jolla, run by the campus ACM chapter with a strong beginner track.',
      'Hackathon',
      'College Students / All Skill Levels',
      '/resources/hackathons/diamondhacks.png',
      'https://www.mlh.com/seasons/2027/events',
      'Expected',
      'Event set for Apr 4-5, 2027; applications expected Feb-Mar 2027',
      'Confirmed on the MLH 2027 season schedule.',
      null::date,
      null::date,
      38
    ),
    (
      'LA Hacks 27',
      'One of the largest hackathons on the West Coast, held each spring at UCLA with a heavy venture-capital and startup presence.',
      'Hackathon',
      'College Students / All Skill Levels',
      '/resources/hackathons/la-hacks-27.png',
      'https://www.lahacks.com/',
      'Expected',
      'Event set for Apr 16-18, 2027; applications expected Feb-Mar 2027',
      'Confirmed on the MLH 2027 season schedule.',
      null::date,
      null::date,
      39
    ),
    (
      'Hack the North',
      'Canada’s largest hackathon, free to attend with travel and accommodation support, and one of the most competitive admits in North America.',
      'Hackathon',
      'Students Worldwide / Highly Selective',
      '/resources/hackathons/hack-the-north.png',
      'https://hackthenorth.com/',
      'Watch',
      'Hacker applications are closed for the Sep 18-20, 2026 event',
      'Hacker applications closed before the season began; volunteer applications ran until Aug 28, 2026. Watch for the 2027 cycle to open next summer.',
      null::date,
      null::date,
      40
    ),
    (
      'HackMIT',
      'MIT’s flagship hackathon, one of the most selective student hackathons in the world, with a puzzle-based early admission track.',
      'Hackathon',
      'College Students / Highly Selective',
      '/resources/hackathons/hackmit.png',
      'https://hackmit.org/',
      'Watch',
      'Closed for 2026; applications ended Jul 4, 2026',
      'The 2026 event runs Sep 19-20. Decisions went out in late July with confirmations due early August. Expect the 2027 application to open around May-June.',
      null::date,
      null::date,
      41
    )
) as v(
  title,
  description,
  tag,
  eligibility,
  image,
  link,
  timeline_status,
  timeline,
  previous_timeline,
  opens_on,
  closes_on,
  sort_order
)
where not exists (
  select 1 from public.programs p where p.title = v.title
);

-- Keep re-runs in sync if an event's dates move.
update public.programs as p
set
  description       = v.description,
  tag               = v.tag,
  eligibility       = v.eligibility,
  image             = v.image,
  link              = v.link,
  timeline_status   = v.timeline_status,
  timeline          = v.timeline,
  deadline          = v.timeline,
  previous_timeline = v.previous_timeline,
  opens_on          = v.opens_on,
  closes_on         = v.closes_on,
  sort_order        = v.sort_order,
  source_checked_on = date '2026-09-02'
from (
  values
    (
      'GirlHacks',
      '24-hour hackathon run by NJIT’s Women in Computing Society, built around women and non-binary hackers. Beginner friendly, and all genders may attend.',
      'Hackathon',
      'College Students / All Skill Levels',
      '/resources/hackathons/girlhacks.png',
      'https://www.njitgirlhacks.com/',
      'Open now',
      'Registration closes Sep 9, 2026; event runs Oct 3-4',
      'Deadline confirmed on the GirlHacks site. Held annually at NJIT each fall.',
      null::date,
      date '2026-09-09',
      20
    ),
    (
      'Cal Hacks 13.0',
      'Berkeley’s flagship 36-hour hackathon, one of the largest collegiate hackathons in the world, held at the Palace of Fine Arts in San Francisco.',
      'Hackathon',
      'Undergrad, Grad & New Grads (<1 Year)',
      '/resources/hackathons/cal-hacks-13.png',
      'https://www.calhacks.io/',
      'Open now',
      'Priority deadline Sep 13; regular deadline Sep 20, 2026',
      'Priority decisions Sep 17, regular decisions Sep 25. Students who graduated before Fall 2025 do not qualify.',
      null::date,
      date '2026-09-20',
      21
    ),
    (
      'DivHacks',
      'Columbia’s 32-hour diversity hackathon. The 2026 theme, "Concrete Jungle," focuses on food, housing, and transportation in the communities we live in.',
      'Hackathon',
      'Any College Student, 18+',
      '/resources/hackathons/divhacks.png',
      'https://www.columbiadivhacks.org/',
      'Open now',
      'Applications open now; event runs Sep 26-27, 2026',
      'No published cutoff date — DivHacks accepts applications until it fills. No coding experience or CS major required.',
      null::date,
      null::date,
      22
    ),
    (
      'HackHarvard',
      'A 36-hour undergraduate hackathon drawing 500+ students worldwide to Harvard’s campus, with tracks spanning health, climate, and civic tech.',
      'Hackathon',
      'Undergraduate Students',
      '/resources/hackathons/hackharvard.png',
      'https://www.hhuh.io/',
      'Open now',
      'Applications open now; event runs Oct 16-18, 2026',
      'Harvard is not providing overnight housing this year; plan lodging yourself. Financial aid details are shared with accepted hackers.',
      null::date,
      null::date,
      23
    ),
    (
      'Hack Knight',
      'CUNY Queens College’s student-run diversity hackathon, one of the most accessible entry points into hackathons for NYC commuter students.',
      'Hackathon',
      'College Students / All Skill Levels',
      '/resources/hackathons/hack-knight.png',
      'https://hack-knight.devpost.com/',
      'Opens soon',
      'Event runs Oct 9-11, 2026; application date not published',
      'The Fall 2025 edition ran Oct 17-19 at Queens College.',
      null::date,
      null::date,
      24
    ),
    (
      'SBUHacks',
      'Stony Brook’s largest annual hackathon, where student teams build themed projects from scratch over a weekend on Long Island.',
      'Hackathon',
      'College Students / All Skill Levels',
      '/resources/hackathons/sbuhacks.png',
      'https://hack.sbcs.io/',
      'Open now',
      'Applications open now; event runs Oct 23-25, 2026',
      'This is Stony Brook’s 6th student-run hackathon. No cutoff date published.',
      null::date,
      null::date,
      25
    ),
    (
      'MakeCU',
      'Columbia Robotics Club’s 24-hour hardware hackathon — a rare build-with-your-hands event in NYC, with parts, workshops, and mentors provided.',
      'Hardware',
      'Undergraduate through PhD',
      '/resources/hackathons/makecu.png',
      'https://www.makecu.dev/',
      'Opens soon',
      'Event runs Nov 7-8, 2026; application date not published',
      'Beginners are explicitly welcome — workshops and mentors help you learn hardware during the event.',
      null::date,
      null::date,
      26
    ),
    (
      'BigRed//Hacks',
      'Cornell’s flagship student-run hackathon, a weekend-long build in Ithaca that draws teams from across the Northeast.',
      'Hackathon',
      'College Students / All Skill Levels',
      '/resources/hackathons/bigred-hacks.png',
      'https://www.bigredhacks.com/',
      'Open now',
      'Event runs Oct 2-4, 2026; apply on the event site',
      'Listed on the MLH 2027 season schedule. No public application cutoff date.',
      null::date,
      null::date,
      27
    ),
    (
      'HackRPI 2026',
      'RPI’s 13th annual intercollegiate hackathon, themed "In the Clouds." Free to attend with food, swag, and prizes, open to any school or major.',
      'Hackathon',
      'All Students / Any Major',
      '/resources/hackathons/hackrpi.png',
      'https://www.hackrpi.com/',
      'Opens soon',
      'Event runs Nov 7-8, 2026; register through MLH',
      'Free to attend and open to students from all schools regardless of major or experience level.',
      null::date,
      null::date,
      28
    ),
    (
      'HackHERS',
      'Rutgers’ diversity-focused hackathon centering women and non-binary students, and the main spring hackathon in central New Jersey.',
      'Hackathon',
      'College Students / All Skill Levels',
      '/resources/hackathons/hackhers.png',
      'https://www.mlh.com/seasons/2027/events',
      'Expected',
      'Event set for Feb 27-28, 2027; applications expected Jan 2027',
      'Confirmed on the MLH 2027 season schedule. Spring hackathons typically open applications 4-6 weeks ahead.',
      null::date,
      null::date,
      29
    ),
    (
      'WiCHacks',
      'RIT’s all-women and non-binary hackathon, one of the longest-running diversity hackathons in New York State.',
      'Hackathon',
      'College Students / All Skill Levels',
      '/resources/hackathons/wichacks.png',
      'https://www.mlh.com/seasons/2027/events',
      'Expected',
      'Event set for Feb 27-28, 2027; applications expected Jan 2027',
      'Confirmed on the MLH 2027 season schedule.',
      null::date,
      null::date,
      30
    ),
    (
      'ShellHacks',
      'Florida’s largest hackathon, hosted by INIT at FIU, drawing well over a thousand students to Miami each fall.',
      'Hackathon',
      'College Students / All Skill Levels',
      '/resources/hackathons/shellhacks.png',
      'https://shellhacks.net/',
      'Open now',
      'Event runs Sep 25-27, 2026; register at shellhacks.net',
      'Confirmed on the MLH 2027 season schedule. No public application cutoff date.',
      null::date,
      null::date,
      31
    ),
    (
      'Knight Hacks IX',
      'UCF’s 36-hour flagship hackathon built around curiosity, creativity, and community, and one of the biggest in the Southeast.',
      'Hackathon',
      'College Students / All Skill Levels',
      '/resources/hackathons/knight-hacks.png',
      'https://2026.knighthacks.org/',
      'Open now',
      'Event runs Oct 9-11, 2026; apply at 2026.knighthacks.org',
      'Confirmed on the MLH 2027 season schedule. No public application cutoff date.',
      null::date,
      null::date,
      32
    ),
    (
      'SwampHacks XII',
      'UF’s long-running hackathon, now in its twelfth year, bringing student teams to Gainesville for a weekend build.',
      'Hackathon',
      'College Students / All Skill Levels',
      '/resources/hackathons/swamphacks.png',
      'https://swamphacks.com/',
      'Open now',
      'Event runs Oct 16-18, 2026; hacker applications open in July',
      'Confirmed on the MLH 2027 season schedule. SwampHacks historically opens hacker applications in July.',
      null::date,
      null::date,
      33
    ),
    (
      'Gator Quant Hacks',
      'A quantitative-finance hackathon at UF for students targeting trading, quant research, and financial engineering roles.',
      'Quant',
      'College Students / Quant Interest',
      '/resources/hackathons/gator-quant-hacks.png',
      'https://www.mlh.com/seasons/2027/events',
      'Open now',
      'Event runs Oct 2-4, 2026; apply through the event site',
      'Listed as a diversity event on the MLH 2027 season schedule.',
      null::date,
      null::date,
      34
    ),
    (
      'LA Hacks AI Hackathon',
      'The fall AI-focused edition run by the LA Hacks team, a shorter companion event to their spring flagship at UCLA.',
      'Hackathon',
      'College Students / All Skill Levels',
      '/resources/hackathons/la-hacks-ai.png',
      'https://www.lahacks.com/',
      'Open now',
      'Event runs Oct 17-18, 2026; apply at lahacks.com',
      'Confirmed on the MLH 2027 season schedule.',
      null::date,
      null::date,
      35
    ),
    (
      'TreeHacks',
      'Stanford’s flagship hackathon and one of the most selective in the world, covering meals, travel, and lodging for accepted hackers.',
      'Hackathon',
      'College Students / Highly Selective',
      '/resources/hackathons/treehacks.png',
      'https://www.treehacks.com/',
      'Expected',
      'Applications expected Nov 2026 for a Feb 2027 event',
      'TreeHacks 2026 ran Feb 13-15, 2026 and drew builders from ~30 universities across 12 countries. 2027 dates are not confirmed on the official site.',
      null::date,
      null::date,
      36
    ),
    (
      'SF Hacks',
      'San Francisco State’s student-run hackathon, an accessible Bay Area option that draws heavily from local startups for mentorship.',
      'Hackathon',
      'College Students / All Skill Levels',
      '/resources/hackathons/sf-hacks.png',
      'https://www.mlh.com/seasons/2027/events',
      'Expected',
      'Event set for Feb 19-21, 2027; applications expected Jan 2027',
      'Confirmed on the MLH 2027 season schedule.',
      null::date,
      null::date,
      37
    ),
    (
      'Diamondhacks',
      'UC San Diego’s spring hackathon in La Jolla, run by the campus ACM chapter with a strong beginner track.',
      'Hackathon',
      'College Students / All Skill Levels',
      '/resources/hackathons/diamondhacks.png',
      'https://www.mlh.com/seasons/2027/events',
      'Expected',
      'Event set for Apr 4-5, 2027; applications expected Feb-Mar 2027',
      'Confirmed on the MLH 2027 season schedule.',
      null::date,
      null::date,
      38
    ),
    (
      'LA Hacks 27',
      'One of the largest hackathons on the West Coast, held each spring at UCLA with a heavy venture-capital and startup presence.',
      'Hackathon',
      'College Students / All Skill Levels',
      '/resources/hackathons/la-hacks-27.png',
      'https://www.lahacks.com/',
      'Expected',
      'Event set for Apr 16-18, 2027; applications expected Feb-Mar 2027',
      'Confirmed on the MLH 2027 season schedule.',
      null::date,
      null::date,
      39
    ),
    (
      'Hack the North',
      'Canada’s largest hackathon, free to attend with travel and accommodation support, and one of the most competitive admits in North America.',
      'Hackathon',
      'Students Worldwide / Highly Selective',
      '/resources/hackathons/hack-the-north.png',
      'https://hackthenorth.com/',
      'Watch',
      'Hacker applications are closed for the Sep 18-20, 2026 event',
      'Hacker applications closed before the season began; volunteer applications ran until Aug 28, 2026. Watch for the 2027 cycle to open next summer.',
      null::date,
      null::date,
      40
    ),
    (
      'HackMIT',
      'MIT’s flagship hackathon, one of the most selective student hackathons in the world, with a puzzle-based early admission track.',
      'Hackathon',
      'College Students / Highly Selective',
      '/resources/hackathons/hackmit.png',
      'https://hackmit.org/',
      'Watch',
      'Closed for 2026; applications ended Jul 4, 2026',
      'The 2026 event runs Sep 19-20. Decisions went out in late July with confirmations due early August. Expect the 2027 application to open around May-June.',
      null::date,
      null::date,
      41
    )
) as v(
  title,
  description,
  tag,
  eligibility,
  image,
  link,
  timeline_status,
  timeline,
  previous_timeline,
  opens_on,
  closes_on,
  sort_order
)
where p.title = v.title;
